[package]
name = "hostcall_echo"
version = "0.1.0"
authors = ["Andrew Osheroff <andrewosh@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
hypermachine = { path = "../../libraries/rust" }
serde = "1.0.116"
serde_derive = "1.0.116"
