[package]
name = "hypermachines_sys"
version = "0.1.0"
authors = ["Andrew Osheroff <andrewosh@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["rlib"]

[dependencies]
serde = "1.0.116"
byteorder = "1.3.4"
serde_cbor = "0.11.1"
serde_json = "1.0.58"
serde-json-wasm = "0.2.1"
